#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : inverter.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Sep 04 21:11:05 +1200 2022
# SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: inverter.sh [-help]
# usage: inverter.sh [-lib_map_path]
# usage: inverter.sh [-noclean_files]
# usage: inverter.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'inverter.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_11 processing_system7_vip_v1_0_13 xil_defaultlib generic_baseblocks_v2_1_0 axi_register_slice_v2_1_25 fifo_generator_v13_2_6 axi_data_fifo_v2_1_24 axi_crossbar_v2_1_26 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_14 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_27 xlslice_v1_0_2 axi_utils_v2_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_17 xbip_dsp48_multadd_v3_0_6 dds_compiler_v6_0_21 lib_pkg_v1_0_2 lib_fifo_v1_0_15 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_27 axi_sg_v4_1_14 axi_dma_v7_1_26 xlconcat_v2_1_4 xlconstant_v1_1_7 smartconnect_v1_0 util_vector_logic_v2_0_1 axi_protocol_converter_v2_1_25)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "inverter.sh - Script generated by export_simulation (Vivado v2021.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_11 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/63b7/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_processing_system7_0_0/sim/inverter_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/e1e6/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/8ae1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/fa53/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ac57/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_xbar_0/sim/inverter_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_rst_ps7_0_100M_0/sim/inverter_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_clk_wiz_0_0/inverter_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/inverter/ip/inverter_clk_wiz_0_0/inverter_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/sim/c_ctr_16_bit.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_27 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/a5bb/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_axi_gpio_0_0/sim/INVERTER_BD_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_0_0/sim/INVERTER_BD_xlslice_0_0.v" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_1_0/sim/INVERTER_BD_xlslice_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_1/sim/INVERTER_BD_pwm_cfg_gpio_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_2_0/sim/INVERTER_BD_xlslice_2_0.v" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_2_1/sim/INVERTER_BD_xlslice_2_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_2/sim/INVERTER_BD_pwm_cfg_gpio_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_0_1/sim/INVERTER_BD_xlslice_0_1.v" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_4_0/sim/INVERTER_BD_xlslice_4_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_17 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/dd36/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_21 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/ipshared/7e37/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_dds_compiler_0_1/sim/INVERTER_BD_dds_compiler_0_1.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_dds_compiler_0_2/sim/INVERTER_BD_dds_compiler_0_2.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_dds_compiler_0_3/sim/INVERTER_BD_dds_compiler_0_3.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD_dc_mux_0_0.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD_pwm_generator_0_0.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD_pwm_generator_1_0.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD_pwm_generator_2_0.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD_dc_scaler_0_0.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD_dc_scaler_0_1.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD_dc_scaler_0_2.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/src/dc_mux.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/src/pwm_generator.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/src/dc_scaler.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/sim/INVERTER_BD.vhd" \
    "$ref_dir/../../../bd/inverter/ipshared/55ca/src/INVERTER_BD_wrapper.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/sim/inverter_INVERTER_BD_wrapper_0_2.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_axi_gpio_0_0/sim/inverter_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_xadc_wiz_0_0/inverter_xadc_wiz_0_0_drp_to_axi_stream.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_xadc_wiz_0_0/inverter_xadc_wiz_0_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_xadc_wiz_0_0/inverter_xadc_wiz_0_0_axi_xadc.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_xadc_wiz_0_0/inverter_xadc_wiz_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_15 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/a4ed/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_27 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/9b19/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_14 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/bcf6/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_26 $vhdlan_opts \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/69a4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_axi_dma_0_0/sim/inverter_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_xlconcat_0_0/sim/inverter_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/sim/bd_401b.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_401b_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_401b_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_401b_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_401b_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_401b_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_401b_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_401b_sawn_0.sv" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_401b_swn_0.sv" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_401b_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_401b_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/93a6/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_401b_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_smartconnect_0_0/sim/inverter_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/inverter/ip/inverter_axi_gpio_0_1/sim/inverter_axi_gpio_0_1.vhd" \
    "$ref_dir/../../../bd/inverter/ip/inverter_timebase_generator_0_0/sim/inverter_timebase_generator_0_0.vhd" \
    "$ref_dir/../../../bd/inverter/sim/inverter.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_fifo_generator_0_0/sim/inverter_fifo_generator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3f90/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_util_vector_logic_0_0/sim/inverter_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/8fe4/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/62b6" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../sineInverter.gen/sources_1/bd/inverter/ipshared/66be/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/inverter/ip/inverter_auto_pc_0/sim/inverter_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.inverter xil_defaultlib.glbl -o inverter_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./inverter_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./inverter.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key inverter_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc inverter_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./inverter.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: inverter.sh [-help]\n\
Usage: inverter.sh [-lib_map_path]\n\
Usage: inverter.sh [-reset_run]\n\
Usage: inverter.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
