# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/adc_test/adc_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test || ORIG_REF_NAME==adc_test} -quiet] -quiet

# IP: bd/adc_test/ip/adc_test_processing_system7_0_0/adc_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_processing_system7_0_0 || ORIG_REF_NAME==adc_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/adc_test/ip/adc_test_xadc_wiz_0_0/adc_test_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_xadc_wiz_0_0 || ORIG_REF_NAME==adc_test_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/adc_test/ip/adc_test_axis_subset_converter_0_0/adc_test_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_axis_subset_converter_0_0 || ORIG_REF_NAME==adc_test_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/adc_test/ip/adc_test_rst_ps7_0_100M_0/adc_test_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/adc_test/ip/adc_test_axi_dma_0_0/adc_test_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_axi_dma_0_0 || ORIG_REF_NAME==adc_test_axi_dma_0_0} -quiet] -quiet

# IP: bd/adc_test/ip/adc_test_ps7_0_axi_periph_0/adc_test_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==adc_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/adc_test/ip/adc_test_smartconnect_0_0/adc_test_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_smartconnect_0_0 || ORIG_REF_NAME==adc_test_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/bd_67f1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_0/bd_67f1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_1/bd_67f1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_2/bd_67f1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_3/bd_67f1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_4/bd_67f1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_5/bd_67f1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_6/bd_67f1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_7/bd_67f1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_8/bd_67f1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_9/bd_67f1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_10/bd_67f1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/adc_test/ip/adc_test_auto_pc_0/adc_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_test_auto_pc_0 || ORIG_REF_NAME==adc_test_auto_pc_0} -quiet] -quiet

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_processing_system7_0_0/adc_test_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_test_processing_system7_0_0 || ORIG_REF_NAME==adc_test_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_xadc_wiz_0_0/adc_test_xadc_wiz_0_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_xadc_wiz_0_0/adc_test_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_test_xadc_wiz_0_0 || ORIG_REF_NAME==adc_test_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_axis_subset_converter_0_0/adc_test_axis_subset_converter_0_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_rst_ps7_0_100M_0/adc_test_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_test_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_rst_ps7_0_100M_0/adc_test_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_test_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_axi_dma_0_0/adc_test_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_test_axi_dma_0_0 || ORIG_REF_NAME==adc_test_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_axi_dma_0_0/adc_test_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_test_axi_dma_0_0 || ORIG_REF_NAME==adc_test_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_1/bd_67f1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_1/bd_67f1_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_5/bd_67f1_s00a2s_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_6/bd_67f1_sawn_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_7/bd_67f1_swn_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_8/bd_67f1_sbn_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/bd_0/ip/ip_9/bd_67f1_m00s2a_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_smartconnect_0_0/ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/ip/adc_test_auto_pc_0/adc_test_auto_pc_0_ooc.xdc

# XDC: c:/GIT/bldc-driver-fpga/hardware_design/vivado_project/adc-test/adc-test.gen/sources_1/bd/adc_test/adc_test_ooc.xdc
