set_property IOSTANDARD LVCMOS33 [get_ports U_H]
set_property IOSTANDARD LVCMOS33 [get_ports U_L]
set_property IOSTANDARD LVCMOS33 [get_ports V_H]
set_property IOSTANDARD LVCMOS33 [get_ports V_L]
set_property IOSTANDARD LVCMOS33 [get_ports W_H]
set_property IOSTANDARD LVCMOS33 [get_ports W_L]
