set_property IOSTANDARD LVCMOS33 [get_ports U_H]
set_property IOSTANDARD LVCMOS33 [get_ports U_L]
set_property IOSTANDARD LVCMOS33 [get_ports V_H]
set_property IOSTANDARD LVCMOS33 [get_ports V_L]
set_property IOSTANDARD LVCMOS33 [get_ports W_H]
set_property IOSTANDARD LVCMOS33 [get_ports W_L]

set_property PACKAGE_PIN N17 [get_ports U_H]
set_property PACKAGE_PIN P18 [get_ports U_L]
set_property PACKAGE_PIN R17 [get_ports V_H]
set_property PACKAGE_PIN F16 [get_ports V_L]
set_property PACKAGE_PIN V18 [get_ports W_H]
set_property PACKAGE_PIN V17 [get_ports W_L]
