# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/clarke_hls_test/clarke_hls_test.srcs/sources_1/ip/inverse_clarke_0/inverse_clarke_0.xci
# IP: The module: 'inverse_clarke_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/clarke_hls_test/clarke_hls_test.gen/sources_1/ip/inverse_clarke_0/constraints/inverse_clarke_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inverse_clarke_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/clarke_hls_test/clarke_hls_test.srcs/sources_1/ip/inverse_clarke_0/inverse_clarke_0.xci
# IP: The module: 'inverse_clarke_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/clarke_hls_test/clarke_hls_test.gen/sources_1/ip/inverse_clarke_0/constraints/inverse_clarke_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inverse_clarke_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
