#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_local_deadlock", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("dds_TDATA", 16, hls_in, 0, "axis", "in_data", 1),
	Port_Property("dds_TVALID", 1, hls_in, 4, "axis", "in_vld", 1),
	Port_Property("dds_TREADY", 1, hls_out, 4, "axis", "in_acc", 1),
	Port_Property("dds_TKEEP", 2, hls_in, 1, "axis", "in_data", 1),
	Port_Property("dds_TSTRB", 2, hls_in, 2, "axis", "in_data", 1),
	Port_Property("dds_TUSER", 2, hls_in, 3, "axis", "in_data", 1),
	Port_Property("dds_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("scale", 16, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("u", 16, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("u_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("v", 16, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("v_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("w", 16, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("w_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "dds_scaler";
