# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/c_ctr_16_bit/c_ctr_16_bit.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_ctr_16_bit || ORIG_REF_NAME==c_ctr_16_bit} -quiet] -quiet

# Block Designs: bd/INVERTER_BD/INVERTER_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD || ORIG_REF_NAME==INVERTER_BD} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_xlslice_0_0/INVERTER_BD_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_0_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_0_0} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_xlslice_1_0/INVERTER_BD_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_1_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_1_0} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_dds_compiler_0_0/INVERTER_BD_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_dds_compiler_0_0 || ORIG_REF_NAME==INVERTER_BD_dds_compiler_0_0} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_1 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_1} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_dds_scaler_0_0/INVERTER_BD_dds_scaler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_dds_scaler_0_0 || ORIG_REF_NAME==INVERTER_BD_dds_scaler_0_0} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_pwm_generator_0_0/INVERTER_BD_pwm_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_generator_0_0 || ORIG_REF_NAME==INVERTER_BD_pwm_generator_0_0} -quiet] -quiet

# IP: ip/c_ctr_16_bit/c_ctr_16_bit.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_ctr_16_bit || ORIG_REF_NAME==c_ctr_16_bit} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_pwm_generator_1_0/INVERTER_BD_pwm_generator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_generator_1_0 || ORIG_REF_NAME==INVERTER_BD_pwm_generator_1_0} -quiet] -quiet

# IP: ip/c_ctr_16_bit/c_ctr_16_bit.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_ctr_16_bit || ORIG_REF_NAME==c_ctr_16_bit} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_pwm_generator_2_0/INVERTER_BD_pwm_generator_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_generator_2_0 || ORIG_REF_NAME==INVERTER_BD_pwm_generator_2_0} -quiet] -quiet

# IP: ip/c_ctr_16_bit/c_ctr_16_bit.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_ctr_16_bit || ORIG_REF_NAME==c_ctr_16_bit} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_xlslice_2_0/INVERTER_BD_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_2_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_2_0} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_xlslice_2_1/INVERTER_BD_xlslice_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_2_1 || ORIG_REF_NAME==INVERTER_BD_xlslice_2_1} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_dc_mux_0_0/INVERTER_BD_dc_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_dc_mux_0_0 || ORIG_REF_NAME==INVERTER_BD_dc_mux_0_0} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_2 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_2} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_xlslice_0_1/INVERTER_BD_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_0_1 || ORIG_REF_NAME==INVERTER_BD_xlslice_0_1} -quiet] -quiet

# IP: bd/INVERTER_BD/ip/INVERTER_BD_xlslice_4_0/INVERTER_BD_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_4_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_4_0} -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_1 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_1 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_dds_scaler_0_0/constraints/dds_scaler_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_2 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/ip/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_2 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/inverter_block/inverter_block.gen/sources_1/bd/INVERTER_BD/INVERTER_BD_ooc.xdc
