# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_z1.xdc

# Block Designs: bd/tadc/tadc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc || ORIG_REF_NAME==tadc} -quiet] -quiet

# IP: bd/tadc/ip/tadc_processing_system7_0_0/tadc_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_processing_system7_0_0 || ORIG_REF_NAME==tadc_processing_system7_0_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_xadc_wiz_0_0/tadc_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_xadc_wiz_0_0 || ORIG_REF_NAME==tadc_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_axi_gpio_0_0/tadc_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_axi_gpio_0_0 || ORIG_REF_NAME==tadc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_axis_split_0_0/tadc_axis_split_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_axis_split_0_0 || ORIG_REF_NAME==tadc_axis_split_0_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_axi_gpio_1_0/tadc_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_axi_gpio_1_0 || ORIG_REF_NAME==tadc_axi_gpio_1_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_gpio_data0_0/tadc_gpio_data0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_gpio_data0_0 || ORIG_REF_NAME==tadc_gpio_data0_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_xbar_0/tadc_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_xbar_0 || ORIG_REF_NAME==tadc_xbar_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_ps7_0_axi_periph_0/tadc_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_ps7_0_axi_periph_0 || ORIG_REF_NAME==tadc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_rst_ps7_0_100M_0/tadc_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_rst_ps7_0_100M_0 || ORIG_REF_NAME==tadc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/tadc/ip/tadc_auto_pc_0/tadc_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tadc_auto_pc_0 || ORIG_REF_NAME==tadc_auto_pc_0} -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_processing_system7_0_0/tadc_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_processing_system7_0_0 || ORIG_REF_NAME==tadc_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_xadc_wiz_0_0/tadc_xadc_wiz_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_xadc_wiz_0_0/tadc_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_xadc_wiz_0_0 || ORIG_REF_NAME==tadc_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_axi_gpio_0_0/tadc_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_axi_gpio_0_0 || ORIG_REF_NAME==tadc_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_axi_gpio_0_0/tadc_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_axi_gpio_0_0/tadc_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_axi_gpio_0_0 || ORIG_REF_NAME==tadc_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_axi_gpio_1_0/tadc_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_axi_gpio_1_0 || ORIG_REF_NAME==tadc_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_axi_gpio_1_0/tadc_axi_gpio_1_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_axi_gpio_1_0/tadc_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_axi_gpio_1_0 || ORIG_REF_NAME==tadc_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_gpio_data0_0/tadc_gpio_data0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_gpio_data0_0 || ORIG_REF_NAME==tadc_gpio_data0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_gpio_data0_0/tadc_gpio_data0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_gpio_data0_0/tadc_gpio_data0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_gpio_data0_0 || ORIG_REF_NAME==tadc_gpio_data0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_rst_ps7_0_100M_0/tadc_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_rst_ps7_0_100M_0 || ORIG_REF_NAME==tadc_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_rst_ps7_0_100M_0/tadc_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==tadc_rst_ps7_0_100M_0 || ORIG_REF_NAME==tadc_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/ip/tadc_auto_pc_0/tadc_auto_pc_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/tadc/tadc.gen/sources_1/bd/tadc/tadc_ooc.xdc
