# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq-z1-focshield1_1.xdc

# IP: ip/tick_gen/tick_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tick_gen || ORIG_REF_NAME==tick_gen} -quiet] -quiet

# IP: ip/timbase_ctr/timbase_ctr.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==timbase_ctr || ORIG_REF_NAME==timbase_ctr} -quiet] -quiet

# Block Designs: bd/inverter/inverter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter || ORIG_REF_NAME==inverter} -quiet] -quiet

# IP: bd/inverter/ip/inverter_processing_system7_0_0/inverter_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_processing_system7_0_0 || ORIG_REF_NAME==inverter_processing_system7_0_0} -quiet] -quiet

# IP: bd/inverter/ip/inverter_xbar_0/inverter_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_xbar_0 || ORIG_REF_NAME==inverter_xbar_0} -quiet] -quiet

# IP: bd/inverter/ip/inverter_axi_interconnect_0_0/inverter_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_axi_interconnect_0_0 || ORIG_REF_NAME==inverter_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/inverter/ip/inverter_rst_ps7_0_100M_0/inverter_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_rst_ps7_0_100M_0 || ORIG_REF_NAME==inverter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/inverter/ip/inverter_clk_wiz_0_0/inverter_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_clk_wiz_0_0 || ORIG_REF_NAME==inverter_clk_wiz_0_0} -quiet] -quiet

# IP: bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/inverter_INVERTER_BD_wrapper_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_INVERTER_BD_wrapper_0_2 || ORIG_REF_NAME==inverter_INVERTER_BD_wrapper_0_2} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_dds_compiler_0_3/INVERTER_BD_dds_compiler_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_dds_compiler_0_3 || ORIG_REF_NAME==INVERTER_BD_dds_compiler_0_3} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_dds_compiler_0_2/INVERTER_BD_dds_compiler_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_dds_compiler_0_2 || ORIG_REF_NAME==INVERTER_BD_dds_compiler_0_2} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_dds_compiler_0_1/INVERTER_BD_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_dds_compiler_0_1 || ORIG_REF_NAME==INVERTER_BD_dds_compiler_0_1} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_4_0/INVERTER_BD_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_4_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_4_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_0_1/INVERTER_BD_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_0_1 || ORIG_REF_NAME==INVERTER_BD_xlslice_0_1} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_2 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_2} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_2_1/INVERTER_BD_xlslice_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_2_1 || ORIG_REF_NAME==INVERTER_BD_xlslice_2_1} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_2_0/INVERTER_BD_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_2_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_2_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_1 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_1} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_1_0/INVERTER_BD_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_1_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_1_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_xlslice_0_0/INVERTER_BD_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_0_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/c_ctr_16_bit/c_ctr_16_bit.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_ctr_16_bit || ORIG_REF_NAME==c_ctr_16_bit} -quiet] -quiet

# IP: bd/inverter/ip/inverter_timebase_generator_0_0/inverter_timebase_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_timebase_generator_0_0 || ORIG_REF_NAME==inverter_timebase_generator_0_0} -quiet] -quiet

# IP: ip/tick_gen/tick_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tick_gen || ORIG_REF_NAME==tick_gen} -quiet] -quiet

# IP: ip/timbase_ctr/timbase_ctr.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==timbase_ctr || ORIG_REF_NAME==timbase_ctr} -quiet] -quiet

# IP: bd/inverter/ip/inverter_axi_gpio_0_0/inverter_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_axi_gpio_0_0 || ORIG_REF_NAME==inverter_axi_gpio_0_0} -quiet] -quiet

# IP: bd/inverter/ip/inverter_auto_pc_0/inverter_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_auto_pc_0 || ORIG_REF_NAME==inverter_auto_pc_0} -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_processing_system7_0_0/inverter_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_processing_system7_0_0 || ORIG_REF_NAME==inverter_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_rst_ps7_0_100M_0/inverter_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_rst_ps7_0_100M_0 || ORIG_REF_NAME==inverter_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_rst_ps7_0_100M_0/inverter_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_rst_ps7_0_100M_0 || ORIG_REF_NAME==inverter_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_clk_wiz_0_0/inverter_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_clk_wiz_0_0 || ORIG_REF_NAME==inverter_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_clk_wiz_0_0/inverter_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_clk_wiz_0_0 || ORIG_REF_NAME==inverter_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_clk_wiz_0_0/inverter_clk_wiz_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_2 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_2/INVERTER_BD_pwm_cfg_gpio_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_2 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_1 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_pwm_cfg_gpio_1/INVERTER_BD_pwm_cfg_gpio_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_pwm_cfg_gpio_1 || ORIG_REF_NAME==INVERTER_BD_pwm_cfg_gpio_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_INVERTER_BD_wrapper_0_2/src/INVERTER_BD_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_axi_gpio_0_0/inverter_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_axi_gpio_0_0 || ORIG_REF_NAME==inverter_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_axi_gpio_0_0/inverter_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_axi_gpio_0_0/inverter_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_axi_gpio_0_0 || ORIG_REF_NAME==inverter_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/ip/inverter_auto_pc_0/inverter_auto_pc_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/vivado_project/sineInverter/sineInverter.gen/sources_1/bd/inverter/inverter_ooc.xdc
