set_property IOSTANDARD LVCMOS33 [get_ports INHA]
set_property IOSTANDARD LVCMOS33 [get_ports INHB]
set_property IOSTANDARD LVCMOS33 [get_ports INHC]
set_property IOSTANDARD LVCMOS33 [get_ports INLA]
set_property IOSTANDARD LVCMOS33 [get_ports INLB]
set_property IOSTANDARD LVCMOS33 [get_ports INLC]
set_property PACKAGE_PIN V17 [get_ports INHA]
set_property PACKAGE_PIN V18 [get_ports INHB]
set_property PACKAGE_PIN T16 [get_ports INHC]
set_property PACKAGE_PIN R17 [get_ports INLA]
set_property PACKAGE_PIN P18 [get_ports INLB]
set_property PACKAGE_PIN N17 [get_ports INLC]

set_property IOSTANDARD LVCMOS33 [get_ports indicator_0]
set_property PACKAGE_PIN N15 [get_ports indicator_0]
