set_property IOSTANDARD LVCMOS33 [get_ports INHA]
set_property IOSTANDARD LVCMOS33 [get_ports INHB]
set_property IOSTANDARD LVCMOS33 [get_ports INHC]
set_property IOSTANDARD LVCMOS33 [get_ports INLA]
set_property IOSTANDARD LVCMOS33 [get_ports INLB]
set_property IOSTANDARD LVCMOS33 [get_ports INLC]
set_property PACKAGE_PIN V17 [get_ports INHA]
set_property PACKAGE_PIN V18 [get_ports INHB]
set_property PACKAGE_PIN T16 [get_ports INHC]
set_property PACKAGE_PIN R17 [get_ports INLA]
set_property PACKAGE_PIN P18 [get_ports INLB]
set_property PACKAGE_PIN N17 [get_ports INLC]

set_property IOSTANDARD LVCMOS33 [get_ports indicator_0]
set_property PACKAGE_PIN N15 [get_ports indicator_0]

set_property PACKAGE_PIN D18 [get_ports Vaux1_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux1_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux6_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux6_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux9_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux9_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports full]
set_property PACKAGE_PIN G14 [get_ports full]
