# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynqz1_bldc_driver_rev1.xdc

# Block Designs: bd/inverter_test/inverter_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test || ORIG_REF_NAME==inverter_test} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/inverter_test_INVERTER_BD_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_INVERTER_BD_wrapper_0_0 || ORIG_REF_NAME==inverter_test_INVERTER_BD_wrapper_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/INVERTER_BD_xlslice_1_0/INVERTER_BD_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_1_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_1_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/INVERTER_BD_xlslice_0_0/INVERTER_BD_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_xlslice_0_0 || ORIG_REF_NAME==INVERTER_BD_xlslice_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/c_ctr_16_bit/c_ctr_16_bit.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_ctr_16_bit || ORIG_REF_NAME==c_ctr_16_bit} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_xlconcat_0_0/inverter_test_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_xlconcat_0_0 || ORIG_REF_NAME==inverter_test_xlconcat_0_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_xlconcat_0_1/inverter_test_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_xlconcat_0_1 || ORIG_REF_NAME==inverter_test_xlconcat_0_1} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_xlconcat_1_0/inverter_test_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_xlconcat_1_0 || ORIG_REF_NAME==inverter_test_xlconcat_1_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_processing_system7_0_0/inverter_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_processing_system7_0_0 || ORIG_REF_NAME==inverter_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_xbar_0/inverter_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_xbar_0 || ORIG_REF_NAME==inverter_test_xbar_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_auto_pc_0/inverter_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_auto_pc_0 || ORIG_REF_NAME==inverter_test_auto_pc_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_axi_interconnect_0_0/inverter_test_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_axi_interconnect_0_0 || ORIG_REF_NAME==inverter_test_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_rst_ps7_0_100M_0/inverter_test_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==inverter_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_axi_gpio_0_0/inverter_test_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_axi_gpio_0_0 || ORIG_REF_NAME==inverter_test_axi_gpio_0_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_xlconcat_3_0/inverter_test_xlconcat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_xlconcat_3_0 || ORIG_REF_NAME==inverter_test_xlconcat_3_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_axi_gpio_0_1/inverter_test_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_axi_gpio_0_1 || ORIG_REF_NAME==inverter_test_axi_gpio_0_1} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_xlslice_0_0/inverter_test_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_xlslice_0_0 || ORIG_REF_NAME==inverter_test_xlslice_0_0} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_xlslice_0_1/inverter_test_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_xlslice_0_1 || ORIG_REF_NAME==inverter_test_xlslice_0_1} -quiet] -quiet

# IP: bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/inverter_test_ADC_BLOCK_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inverter_test_ADC_BLOCK_wrapper_0_0 || ORIG_REF_NAME==inverter_test_ADC_BLOCK_wrapper_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_1/ADC_BLOCK_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_BLOCK_axi_gpio_0_1 || ORIG_REF_NAME==ADC_BLOCK_axi_gpio_0_1} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_0/ADC_BLOCK_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_BLOCK_axi_gpio_0_0 || ORIG_REF_NAME==ADC_BLOCK_axi_gpio_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_xlconcat_0_0/ADC_BLOCK_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_BLOCK_xlconcat_0_0 || ORIG_REF_NAME==ADC_BLOCK_xlconcat_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_trigger_module_0_0/ADC_BLOCK_trigger_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_BLOCK_trigger_module_0_0 || ORIG_REF_NAME==ADC_BLOCK_trigger_module_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_trigger_module_0_0/src/ctr_32b/ctr_32b.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ctr_32b || ORIG_REF_NAME==ctr_32b} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_xadc_wiz_0_0/ADC_BLOCK_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ADC_BLOCK_xadc_wiz_0_0 || ORIG_REF_NAME==ADC_BLOCK_xadc_wiz_0_0} -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/INVERTER_BD_axi_gpio_0_0/INVERTER_BD_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==INVERTER_BD_axi_gpio_0_0 || ORIG_REF_NAME==INVERTER_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_INVERTER_BD_wrapper_0_0/src/INVERTER_BD_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_processing_system7_0_0/inverter_test_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_test_processing_system7_0_0 || ORIG_REF_NAME==inverter_test_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_auto_pc_0/inverter_test_auto_pc_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_rst_ps7_0_100M_0/inverter_test_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==inverter_test_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_rst_ps7_0_100M_0/inverter_test_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==inverter_test_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_axi_gpio_0_0/inverter_test_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_test_axi_gpio_0_0 || ORIG_REF_NAME==inverter_test_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_axi_gpio_0_0/inverter_test_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_axi_gpio_0_0/inverter_test_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_test_axi_gpio_0_0 || ORIG_REF_NAME==inverter_test_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_axi_gpio_0_1/inverter_test_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_test_axi_gpio_0_1 || ORIG_REF_NAME==inverter_test_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_axi_gpio_0_1/inverter_test_axi_gpio_0_1_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_axi_gpio_0_1/inverter_test_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==inverter_test_axi_gpio_0_1 || ORIG_REF_NAME==inverter_test_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_1/ADC_BLOCK_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_BLOCK_axi_gpio_0_1 || ORIG_REF_NAME==ADC_BLOCK_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_1/ADC_BLOCK_axi_gpio_0_1_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_1/ADC_BLOCK_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_BLOCK_axi_gpio_0_1 || ORIG_REF_NAME==ADC_BLOCK_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_0/ADC_BLOCK_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_BLOCK_axi_gpio_0_0 || ORIG_REF_NAME==ADC_BLOCK_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_0/ADC_BLOCK_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_axi_gpio_0_0/ADC_BLOCK_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_BLOCK_axi_gpio_0_0 || ORIG_REF_NAME==ADC_BLOCK_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_xadc_wiz_0_0/ADC_BLOCK_xadc_wiz_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_xadc_wiz_0_0/ADC_BLOCK_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ADC_BLOCK_xadc_wiz_0_0 || ORIG_REF_NAME==ADC_BLOCK_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/ip/inverter_test_ADC_BLOCK_wrapper_0_0/src/ADC_BLOCK_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/current_sense_test/current_sense_test.gen/sources_1/bd/inverter_test/inverter_test_ooc.xdc
