# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq-z1.xdc

# Block Designs: bd/adc_trig_bd/adc_trig_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd || ORIG_REF_NAME==adc_trig_bd} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_processing_system7_0_0/adc_trig_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_processing_system7_0_0 || ORIG_REF_NAME==adc_trig_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_trigger_module_0_0/adc_trig_bd_trigger_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_trigger_module_0_0 || ORIG_REF_NAME==adc_trig_bd_trigger_module_0_0} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_trigger_module_0_0/src/ctr_32b/ctr_32b.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ctr_32b || ORIG_REF_NAME==ctr_32b} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_0/adc_trig_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_0 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_1/adc_trig_bd_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_1 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_1} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_xbar_0/adc_trig_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_xbar_0 || ORIG_REF_NAME==adc_trig_bd_xbar_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_ps7_0_axi_periph_0/adc_trig_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==adc_trig_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_rst_ps7_0_100M_0/adc_trig_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_trig_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_xadc_wiz_0_0/adc_trig_bd_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_xadc_wiz_0_0 || ORIG_REF_NAME==adc_trig_bd_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_xlslice_0_0/adc_trig_bd_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_xlslice_0_0 || ORIG_REF_NAME==adc_trig_bd_xlslice_0_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_xlconstant_0_0/adc_trig_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_xlconstant_0_0 || ORIG_REF_NAME==adc_trig_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_3/adc_trig_bd_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_3 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_3} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_xlconcat_0_0/adc_trig_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_xlconcat_0_0 || ORIG_REF_NAME==adc_trig_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_xlslice_0_1/adc_trig_bd_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_xlslice_0_1 || ORIG_REF_NAME==adc_trig_bd_xlslice_0_1} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_adc_demux_0_0/adc_trig_bd_adc_demux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_adc_demux_0_0 || ORIG_REF_NAME==adc_trig_bd_adc_demux_0_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_system_ila_0_0/adc_trig_bd_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_system_ila_0_0 || ORIG_REF_NAME==adc_trig_bd_system_ila_0_0} -quiet] -quiet

# Block Designs: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_system_ila_0_0/bd_0/bd_17f9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17f9 || ORIG_REF_NAME==bd_17f9} -quiet] -quiet

# IP: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_system_ila_0_0/bd_0/ip/ip_0/bd_17f9_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_17f9_ila_lib_0 || ORIG_REF_NAME==bd_17f9_ila_lib_0} -quiet] -quiet

# IP: bd/adc_trig_bd/ip/adc_trig_bd_auto_pc_0/adc_trig_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_trig_bd_auto_pc_0 || ORIG_REF_NAME==adc_trig_bd_auto_pc_0} -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_processing_system7_0_0/adc_trig_bd_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_processing_system7_0_0 || ORIG_REF_NAME==adc_trig_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_0/adc_trig_bd_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_0 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_0/adc_trig_bd_axi_gpio_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_0/adc_trig_bd_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_0 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_1/adc_trig_bd_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_1 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_1/adc_trig_bd_axi_gpio_0_1_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_1/adc_trig_bd_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_1 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_rst_ps7_0_100M_0/adc_trig_bd_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_trig_bd_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_rst_ps7_0_100M_0/adc_trig_bd_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_trig_bd_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_xadc_wiz_0_0/adc_trig_bd_xadc_wiz_0_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_xadc_wiz_0_0/adc_trig_bd_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_xadc_wiz_0_0 || ORIG_REF_NAME==adc_trig_bd_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_3/adc_trig_bd_axi_gpio_0_3_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_3 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_3/adc_trig_bd_axi_gpio_0_3_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_axi_gpio_0_3/adc_trig_bd_axi_gpio_0_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==adc_trig_bd_axi_gpio_0_3 || ORIG_REF_NAME==adc_trig_bd_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_17f9_ila_lib_0 || ORIG_REF_NAME==bd_17f9_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_17f9_ila_lib_0 || ORIG_REF_NAME==bd_17f9_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_system_ila_0_0/bd_0/ip/ip_0/bd_17f9_ila_lib_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_system_ila_0_0/bd_0/bd_17f9_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/ip/adc_trig_bd_auto_pc_0/adc_trig_bd_auto_pc_0_ooc.xdc

# XDC: c:/git/bldc-driver-fpga/hardware_design/module_test_projects/adc_triggering_test/adc_triggering_test.gen/sources_1/bd/adc_trig_bd/adc_trig_bd_ooc.xdc
